import { Sport } from '../App';

export interface BingoItem {
  name: string;
  description: string;
}

const soccerItems: BingoItem[] = [
 { name: 'Goal', description: 'The ball fully crosses the goal line between the posts, counting as a score for the attacking team.' },
 { name: 'Corner Kick', description: 'Awarded when the defending team last touches the ball before it crosses their own goal line. The attacking team restarts' },
 { name: 'Yellow Card', description: 'A formal warning issued by the referee to a player for misconduct or a foul.' },
 { name: 'Offside', description: 'An attacking player is called for being ahead of the last defender when the ball is played to them.' },
 { name: 'Penalty', description: 'A direct free kick from the penalty spot, awarded when a foul occurs inside the defending team\'s penalty area.' },
 { name: 'Substitution', description: 'A player is removed from the match and replaced by another from the bench.' },
 { name: 'Header', description: 'A player uses their head to direct or control the ball.' },
 { name: 'Tackle', description: 'A player challenges an opponent to win possession of the ball.' },
 { name: 'Throw-In', description: 'A player throws the ball back into play from the sideline after it goes out of bounds.' },
 { name: 'Assist', description: 'A pass or touch that directly leads to a goal being scored.' },
 { name: 'Red Card', description: 'A player is ejected from the match for serious misconduct or receiving two yellow cards.' },
 { name: 'Free Kick', description: 'Play restarts after a foul with a kick from the spot where the infraction occurred.' },
 { name: 'Free Space', description: 'Free space - automatically marked!' },
 { name: 'Cross', description: 'A player sends the ball from a wide position into the penalty area for teammates to attack.' },
 { name: 'Injury', description: 'A player goes down and requires medical attention on the pitch.' },
 { name: 'Hat Trick', description: 'One player scores three goals in a single match.' },
 { name: 'Volley', description: 'A player strikes the ball out of the air before it touches the ground.' },
 { name: 'Nutmeg', description: 'A player passes the ball through an opponent\'s legs to get past them.' },
 { name: 'Clean Sheet', description: 'The goalkeeper and defense prevent the opposing team from scoring for the entire match.' },
 { name: 'Own Goal', description: 'A player accidentally scores into their own net, giving the opposing team a point.' },
 { name: 'VAR Check', description: 'The Video Assistant Referee reviews a decision made on the pitch, causing a pause in play.' },
 { name: 'Stadium Wave', description: 'Fans stand and raise their arms in sequence around the stadium, creating a ripple effect.' },
 { name: 'Face/Body Paint', description: 'A fan paints their face or body in team colors to show support.' },
 { name: 'Flag Waving', description: 'A fan waves a large team or national flag in the stands.' },
 { name: 'Flares / Smoke', description: '(UK) Colored smoke or flares set off by fans, usually to celebrate or intimidate.' },
 { name: 'Drum Beat', description: 'A fan section keeps a steady beat on drums to rally the crowd.' },
 { name: 'Retro Jersey', description: 'A fan wears a classic jersey from a past era of the club.' },
 { name: 'Fan Hug', description: 'Two or more fans embrace in the stands, usually after a goal.' },
 { name: 'Big Hat', description: 'A fan wearing an oversized or novelty hat in team colors.' },
 { name: 'Team Scarf', description: 'A supporter holds or wears the club\'s official scarf.' },
 { name: 'Fan Tears', description: 'A fan is visibly crying, from joy or heartbreak.' },
 { name: 'Banner', description: 'A large sign or cloth displayed by fans with a message or club crest.' },
 { name: 'Fan Dance', description: 'Fans break into a coordinated or spontaneous dance in the stands.' },
 { name: 'Crowd Roar', description: 'The entire stadium erupts in noise simultaneously.' },
 { name: 'Security Check', description: 'Stadium staff checks a fan or intervenes in the stands.' },
 { name: 'Kickoff', description: 'The match begins or restarts with a player passing the ball from the center circle.' },
 { name: 'Goal Celebration', description: 'Players celebrate together immediately after scoring.' },
 { name: 'Coach Yelling', description: 'Manager shouts instructions or protests from the sideline.' },
 { name: 'Missed Shot', description: 'A player shoots and the ball goes wide, over, or straight at the keeper.' },
 { name: 'Extra Time', description: 'Two additional 15-minute periods played when the match is tied after 90 minutes.' },
 { name: 'Penalty Shootout', description: 'Teams alternate penalty kicks to decide the winner after a drawn match.' },
 { name: 'Slide Tackle', description: 'A player slides along the ground to dispossess an opponent.' },
 { name: 'Knee Slide', description: 'A player celebrates a goal by sliding on their knees across the pitch.' },
 { name: 'Shirt Pull', description: 'A player grabs an opponent\'s jersey, typically to slow them down.' },
 { name: 'Push Foul', description: 'A player shoves an opponent, resulting in a free kick.' },
 { name: 'Bad Tackle', description: 'A dangerous or reckless challenge that endangers the opponent.' },
 { name: 'Clean Tackle', description: 'A perfectly timed challenge that wins the ball without fouling.' },
 { name: 'Header Goal', description: 'A player scores by directing the ball into the net with their head.' },
 { name: 'Manager Yellow Card', description: 'The referee books the manager for misconduct on the touchline.' },
 { name: 'Manager Red Card', description: 'The manager is sent to the stands for serious or repeated misconduct.' },
 { name: 'Injury Tackle', description: 'A tackle that results in a player going down injured.' },
 { name: 'Ball Into Seats', description: 'The ball is kicked or deflected out of play and into the crowd.' },
 { name: 'Missed Pass', description: 'A pass that fails to reach its intended teammate.' },
 { name: 'Ref Bad Call', description: 'The referee makes a decision that players or fans strongly disagree with.' },
 { name: 'Goal Disallowed', description: 'A goal is ruled out, usually for offside or a foul in the buildup.' },
 { name: 'Keeper Save', description: 'The goalkeeper stops a shot from going into the net.' },
 { name: 'Goal Kick', description: 'The goalkeeper kicks the ball back into play after it crosses the goal line, last touched by an attacking player.' },
 { name: 'Double Substitution', description: 'A manager makes two player changes at the same time.' },
 { name: 'Triple Substitution', description: 'A manager makes three player changes simultaneously.' },
 { name: 'Collision Injury', description: 'Physical damage resulting from direct, high-force impact with another player, the ground, or equipment.' },
 { name: 'Post / Crossbar Hit', description: 'A shot strikes the upright or crossbar and stays out of the net.' },
 { name: 'Brace', description: 'One player scores two goals in the same match.' },
 { name: 'Stoppage Time Goal', description: 'A goal scored after the 90th minute during injury time added by the referee.' },
 { name: 'Diving / Simulation', description: 'A player deliberately falls to the ground to deceive the referee into awarding a foul.' },
 { name: 'Long Range Goal', description: 'A goal scored from outside the penalty area, typically 25 yards or more.' },
 { name: 'Offside Trap', description: 'The defensive line steps up simultaneously to catch an attacker offside.' },
 { name: 'Tactical Foul', description: 'A deliberate foul to stop a dangerous counterattack, often resulting in a yellow card.' },
 { name: 'Time Wasting', description: 'A player deliberately delays the game, usually prompting a booking or crowd reaction.' },
 { name: 'Shirt Swap', description: 'Two opposing players exchange jerseys at the end of the match.' },
 { name: 'Wall Jump', description: 'During a free kick, one or more defenders in the wall leap to block a low shot.' },
 { name: 'Bicycle Kick', description: 'A player kicks the ball backwards over their own head while airborne, typically as a shot on goal.' },
 { name: 'Backheel Pass', description: 'A player passes the ball backwards using their heel.' },
 { name: 'National Flag', description: 'A country\'s official flag displayed or worn by supporters.' },
 { name: 'Fan Song', description: 'Supporters sing a recognizable song or rallying anthem together as a group.' },
 { name: '5th Sub Used', description: 'The manager uses their fifth and final substitution of the match.' },
 { name: 'Team Anthem', description: 'The official team or national anthem is played, with fans singing along.' },
 { name: 'Ole Chant', description: 'The crowd chants "Ole!" in rhythm each time their team completes a series of passes, signaling dominance.' },
 //{ name: 'Streaker', description: 'An unclothed person runs across the pitch during the match.' },
 //{ name: 'Pitch Invasion', description: 'A fan or fans enter the playing field during or after the match.' },
 //{ name: 'Goalkeeper Goal', description: 'The goalkeeper scores a goal, either from open play or a direct kick.' },
 //{ name: 'Rabona', description: 'A player wraps their kicking foot behind their standing leg to strike the ball.' },
 //{ name: 'Panenka Penalty', description: 'A penalty taken with a soft chip down the center of the goal while the keeper dives to one side.' },
 //{ name: 'Water Break', description: 'Play is temporarily stopped for players to hydrate, common in hot weather matches.' },
 //{ name: 'Vuvuzela', description: 'A plastic horn blown by fans, famous from the 2010 World Cup in South Africa.' },
 //{ name: 'Ref Protest Sign', description: 'A fan in the stands holds up a visible sign directed at the referee, expressing disagreement with calls made during' },
];

const baseballItems: BingoItem[] = [
 { name: 'Home Run', description: 'A batter hits the ball out of the park, automatically scoring all runners on base including themselves.' },
 { name: 'Strikeout', description: 'A batter receives three strikes and is out, either by swinging and missing or a called third strike.' },
 { name: 'Double Play', description: 'The defense records two outs on a single play, typically a ground ball fielded and thrown to first and second.' },
 { name: 'Walk', description: 'A batter receives four balls and advances to first base without the ball being put in play.' },
 { name: 'Stolen Base', description: 'A baserunner advances to the next base while the pitcher is delivering the ball, without a hit.' },
 { name: 'Fly Out', description: 'A batter hits the ball high into the air and it is caught by a fielder before touching the ground.' },
 { name: 'Ground Out', description: 'A batter hits the ball along the ground and is thrown out at first base.' },
 { name: 'Hit by Pitch', description: 'A batter is struck by a pitched ball and awarded first base.' },
 { name: 'Bunt', description: 'A batter intentionally taps the ball lightly into the infield instead of taking a full swing.' },
 { name: 'Error', description: 'A fielder mishandles a ball in a way that allows a batter or runner to advance when they otherwise would not have.' },
 { name: 'Sacrifice Fly', description: 'A batter hits a fly ball that is caught for an out, but is deep enough to allow a runner to tag up and score.' },
 { name: 'Foul Ball', description: 'A batted ball lands outside the foul lines, counting as a strike unless the batter already has two strikes.' },
 { name: 'Free Space', description: 'Free space - automatically marked!' },
 { name: 'Pitching Change', description: 'The manager removes the current pitcher and brings in a new one from the bullpen.' },
 { name: 'Pop Up', description: 'A batter hits the ball straight up or at a sharp angle, resulting in an easy catch in the infield.' },
 { name: 'Wild Pitch', description: 'A pitcher throws a ball so far outside the strike zone that the catcher cannot control it, allowing runners to advance.' },
 { name: 'Grand Slam', description: 'A home run hit with the bases loaded, scoring four runs at once.' },
 { name: 'Caught Stealing', description: 'A baserunner attempts to steal a base but is thrown out by the catcher.' },
 { name: 'Infield Hit', description: 'A batter reaches base safely on a ball that never leaves the infield.' },
 { name: 'Balk', description: 'The pitcher makes an illegal motion on the mound, advancing all baserunners one base.' },
 { name: 'Diving Catch', description: 'A fielder throws themselves to the ground to catch a ball that would otherwise fall for a hit.' },
 { name: 'RBI', description: 'A batter\'s hit or play directly causes a run to score.' },
 { name: 'Called Strike', description: 'The umpire calls a strike on a pitch the batter did not swing at.' },
 { name: 'Hit', description: 'A batter puts the ball in play and reaches base safely without an error or fielder\'s choice.' },
 { name: 'Single', description: 'A batter hits the ball and reaches first base safely.' },
 { name: 'Double', description: 'A batter hits the ball and reaches second base safely.' },
 { name: 'Triple', description: 'A batter hits the ball and reaches third base safely.' },
 { name: 'Pickoff', description: 'The pitcher throws to a base in an attempt to tag out a baserunner who has strayed too far.' },
 { name: 'Sacrifice Bunt', description: 'A batter intentionally bunts to advance a runner, accepting an out in exchange.' },
 { name: 'Relief Pitcher', description: 'A pitcher who enters the game to replace the starting pitcher.' },
 { name: 'Umpire Call', description: 'The umpire makes a visible call on the field, such as safe, out, or ball and strike.' },
 { name: 'Line Drive', description: 'A batter hits the ball sharply and directly, traveling in a nearly straight line.' },
 { name: 'Tag Out', description: 'A fielder tags a runner with the ball while the runner is off base.' },
 { name: 'Strikeout Looking', description: 'A batter is called out on a third strike without swinging, often drawing a strong crowd reaction.' },
 { name: 'Walk-Off Hit', description: 'A hit in the bottom of the final inning that ends the game with a win for the home team.' },
 { name: 'Hit and Run', description: 'The baserunner starts running as the pitcher delivers, and the batter swings to protect them.' },
 { name: 'Intentional Walk', description: 'The pitcher deliberately throws four balls to avoid pitching to a dangerous batter.' },
 { name: 'Manager Ejection', description: 'The manager is thrown out of the game by the umpire, often after arguing a call.' },
 { name: 'Umpire Argument', description: 'A player or manager charges onto the field to argue a call with the umpire.' },
 { name: 'Replay Review', description: 'The umpires review a disputed call using video replay technology.' },
 { name: 'Extra Innings', description: 'The game is tied after nine innings and continues until a winner is decided.' },
 { name: 'Bases Loaded', description: 'All three bases are occupied by runners simultaneously.' },
 { name: 'Leadoff Home Run', description: 'The first batter of an inning hits a home run.' },
 { name: 'Passed Ball', description: 'The catcher fails to control a pitch they should have caught, allowing a baserunner to advance.' },
 { name: 'ABS Challenge', description: 'A batter or manager challenges an umpire\'s ball or strike call, triggering an automated review system that can overturn the decision.' },
 { name: 'Pitch Clock Violation', description: 'The pitcher or batter exceeds the time limit between pitches, resulting in an automatic ball or strike called against them.' },
 { name: 'Mound Visit', description: 'The manager or pitching coach walks to the mound to talk to the pitcher, pausing play.' },
 { name: 'Pinch Hitter', description: 'A substitute batter enters the game to hit in place of another player, usually for a strategic advantage.' },
 { name: 'Base Coach Interaction', description: 'A base coach visibly signals or talks to a runner, directing their next move on the basepaths.' },
 { name: 'Celebrity in the Stands', description: 'The broadcast cuts to a recognizable celebrity watching the game from the stands.' },
 { name: 'First Hit of the Game', description: 'The first batter to reach base safely on a hit, a notable milestone early in the game.' },
 { name: 'First Run of the Game', description: 'The first run scored by either team, often a turning point in momentum.' },
 { name: 'Bullpen Warmup', description: 'The broadcast shows a relief pitcher warming up in the bullpen before being called into the game.' },
 { name: 'Designated Hitter', description: 'The player who bats in place of the pitcher in the lineup without playing a defensive position in the field.' },
 { name: 'Hot Dog', description: 'A fan is eating a hot dog, the iconic ballpark food.' },
 { name: 'Beer Cup', description: 'A fan is seen with a beer, a staple of the ballpark experience.' },
 { name: 'Cracker Jack', description: 'A fan is seen with the iconic caramel popcorn and peanut snack, immortalized in Take Me Out to the Ballgame.' },
 { name: '7th Inning Stretch', description: 'The crowd stands and sings Take Me Out to the Ballgame between the top and bottom of the seventh inning.' },
 { name: 'Organ Music', description: 'The stadium organ plays between plays or during stoppages, a tradition dating back to the 1940s.' },
 { name: 'National Anthem', description: 'The national anthem is performed before the game begins with fans standing and removing their hats.' },
 { name: 'Stadium Wave', description: 'Fans stand and raise their arms in sequence around the stadium, creating a ripple effect.' },
 { name: 'Face Paint', description: 'A fan has painted their face in team colors.' },
 { name: 'Painted Chest', description: 'A fan has painted their torso in team colors.' },
 { name: 'Retro Jersey', description: 'A fan wears a classic jersey from a past era of the team.' },
 { name: 'Colorful Wig', description: 'A fan wears a brightly colored wig in team colors.' },
 { name: 'Big Hat', description: 'A fan wearing an oversized or novelty hat in team colors.' },
 { name: 'Banner', description: 'A large sign or cloth displayed by fans with a message or team logo.' },
 { name: 'Fan Roar', description: 'The entire stadium erupts in noise simultaneously.' },
 { name: 'High Five', description: 'Fans high five each other in the stands, usually after a big play.' },
 { name: 'Charge Cheer', description: 'The crowd responds to the Charge bugle call in unison.' },
 { name: 'Souvenir Ball Catch', description: 'A fan catches a foul ball or home run ball as a keepsake.' },
 { name: 'Mascot On Field', description: 'The team mascot appears on the field or interacts with fans during a stoppage in play.' },
 //{ name: 'Perfect Game', description: 'A pitcher retires all 27 batters faced without allowing any baserunner. Only 24 have occurred in MLB history.' },
 //{ name: 'No-Hitter', description: 'A pitcher completes a game without allowing any hits, one of the rarest individual achievements in baseball.' },
 //{ name: 'Triple Play', description: 'The defense records three outs on a single play, one of the most exciting and rare defensive moments in baseball.' },
];

const basketballItems: BingoItem[] = [
 { name: '3-Pointer', description: 'A shot made from beyond the arc, worth three points instead of two.' },
 { name: 'Dunk', description: 'A player jumps and forcefully pushes the ball through the basket with one or both hands.' },
 { name: 'Block', description: 'A defensive player legally deflects a shot attempt, preventing it from reaching the basket.' },
 { name: 'Steal', description: 'A defensive player takes the ball away from an offensive player, causing a turnover.' },
 { name: 'Assist', description: 'A pass that directly leads to a made basket by a teammate.' },
 { name: 'Rebound', description: 'A player grabs the ball after a missed shot, either on offense or defense.' },
 { name: 'Free Throw', description: 'An uncontested shot from the free throw line, awarded after certain fouls.' },
 { name: 'Foul', description: 'Illegal physical contact by one player against another, stopping play.' },
 { name: 'Timeout', description: 'A team stops play to huddle with the coach and discuss strategy.' },
 { name: 'Turnover', description: 'A team loses possession of the ball without taking a shot.' },
 { name: 'Alley-Oop', description: 'One player throws a lob pass near the basket and a teammate catches it in the air and dunks or lays it in.' },
 { name: 'Layup', description: 'A close-range shot where a player rolls the ball off the backboard or drops it over the rim.' },
 { name: 'Free Space', description: 'Free space - automatically marked!' },
 { name: 'Double-Double', description: 'A player reaches double digits in two statistical categories in the same game, most commonly points and rebounds.' },
 { name: 'Fast Break', description: 'A team pushes the ball up the court quickly before the defense can set up, creating an easy scoring opportunity.' },
 { name: 'Jump Ball', description: 'Two opposing players contest for the ball held by a referee, who tosses it up between them.' },
 { name: 'Technical Foul', description: 'A foul called for unsportsmanlike conduct, arguing with officials, or a rules violation not involving contact.' },
 { name: 'Buzzer Beater', description: 'A shot made just as the game clock expires, often deciding the outcome.' },
 { name: 'Crossover', description: 'A ball handler quickly switches the ball from one hand to the other to change direction and lose a defender.' },
 { name: 'And-One', description: 'A player is fouled while making a basket, earning one additional free throw attempt.' },
 { name: 'Triple-Double', description: 'A player reaches double digits in three statistical categories in the same game.' },
 { name: 'Traveling', description: 'A player takes too many steps without dribbling, resulting in a turnover.' },
 { name: 'Charge', description: 'A defensive player plants their feet and absorbs contact from an offensive player, drawing an offensive foul.' },
 { name: 'Substitution', description: 'A player on the bench enters the game to replace a player on the court.' },
 { name: 'Bank Shot', description: 'A shot that bounces off the backboard before going into the basket.' },
 { name: 'Double Dribble', description: 'A player dribbles the ball, stops, and then dribbles again, resulting in a turnover.' },
 { name: 'Shot Clock Violation', description: 'A team fails to attempt a shot within the allotted time, resulting in a turnover.' },
 { name: 'Injury', description: 'A player goes down and requires medical attention, stopping play.' },
 { name: 'Coach Yelling', description: 'The head coach shouts instructions or protests a call from the sideline.' },
 { name: 'Tip Off', description: 'The game begins with a jump ball at center court between two opposing players.' },
 { name: 'Missed Free Throw', description: 'A player fails to convert a free throw attempt, drawing a crowd reaction.' },
 { name: 'Air Ball', description: 'A shot attempt that misses the rim, backboard, and net entirely, drawing a loud crowd reaction.' },
 { name: 'Flagrant Foul', description: 'A hard or reckless foul deemed dangerous by the referee, resulting in free throws and possession for the opposing team.' },
 { name: 'Intentional Foul', description: 'A deliberate foul used as a late-game strategy to stop the clock and send the opposing team to the free throw line.' },
 { name: 'Overtime', description: 'The game is tied at the end of regulation and continues with additional five-minute periods until a winner is determined.' },
 { name: 'Ejection', description: 'A player or coach is removed from the game after receiving two technical fouls.' },
 { name: 'Poster Dunk', description: 'A powerful dunk where the offensive player dunks directly over a defender.' },
 { name: 'Ankle Breaker', description: 'A crossover or dribble move so sharp that the defender loses their footing and falls.' },
 { name: 'Half Court Shot', description: 'A shot attempted from half court, usually at the end of a quarter, generating a massive crowd reaction if it goes in.' },
 { name: 'Tip-In', description: 'A player taps a missed shot directly into the basket off the rebound without fully controlling the ball first.' },
 { name: 'No-Look Pass', description: 'A pass made without looking at the intended receiver, designed to fool the defense.' },
 { name: 'Pick and Roll', description: 'A play where one player sets a screen for the ball handler, then rolls toward the basket to receive a pass.' },
 { name: 'Hook Shot', description: 'A one-handed shot where the player sweeps their arm in an arc over their head to release the ball.' },
 { name: 'Fadeaway', description: 'A jump shot taken while leaning away from the defender, making it nearly impossible to block.' },
 { name: 'Mid-Range Jumper', description: 'A jump shot taken from between the paint and the three-point line.' },
 { name: 'Coach Challenge', description: 'A coach uses their one challenge to request a referee review a specific call via video replay.' },
 { name: 'Official Review', description: 'Referees initiate their own video review, typically in the last two minutes of the game for out of bounds, shot clock, or flagrant foul calls.' },
 { name: 'Intentional Miss', description: 'A player deliberately misses a free throw to allow a teammate to grab the rebound, used as a late-game strategy.' },
 { name: 'Foul Trouble', description: 'A player has accumulated enough fouls that the coach benches them to protect them from fouling out.' },
 { name: 'Towel Twirl', description: 'A player on the bench or a fan twirls a towel overhead to energize the crowd or celebrate a big play.' },
 { name: 'Full Court Pass', description: 'A player throws the ball the length of the court, usually to a teammate on a fast break or to beat the shot clock.' },
 { name: 'Loose Ball', description: 'Neither team has possession and both scramble to recover the ball, generating a crowd reaction.' },
 { name: 'Charge Drawn', description: 'A defensive player plants their feet and takes a hard hit from an offensive player, drawing an offensive foul through sheer hustle.' },
 { name: 'Box Out', description: 'A player uses their body to block an opponent from getting position for a rebound.' },
 { name: 'Corner Three', description: 'A three-pointer taken from the corner of the court, the most efficient shot in basketball.' },
 { name: 'Flop', description: 'A player dramatically falls or reacts to minimal contact to deceive the referee into calling a foul.' },
 { name: 'Face Paint', description: 'A fan has painted their face in team colors, often highlighted by broadcast cameras.' },
 { name: 'Colorful Wig', description: 'A fan wears a brightly colored wig in team colors, regularly sought out by broadcast cameras.' },
 { name: 'Big Hat', description: 'A fan wears an oversized or novelty hat, regularly sought out by broadcast cameras.' },
 { name: 'Banner', description: 'A large sign or cloth displayed by fans with a message or team slogan.' },
 { name: 'Mascot On Court', description: 'The team mascot appears on the court during a timeout or stoppage, interacting with fans or performing.' },
 { name: 'Half-Time Show', description: 'Performers, acrobats, or entertainers take the court during halftime.' },
 { name: 'Dance Cam', description: 'The jumbotron highlights a fan dancing energetically in the stands.' },
 { name: 'Celebrity Courtside', description: 'The broadcast cuts to a recognizable celebrity sitting courtside at the game.' },
 { name: 'Player Introductions', description: 'The starting lineup is announced with arena lights, music, and video before tip off.' },
 { name: 'Timeout Performance', description: 'Dancers, acrobats, or other entertainers perform on the court during a timeout stoppage.' },
 { name: 'Courtside Selfie', description: 'A fan sitting courtside is shown taking a selfie, often capturing players or the court in the background.' },
 { name: 'Defense Chant', description: 'The crowd chants "Defense!" in unison, clapping in rhythm to pressure the opposing team.' },
 { name: 'Fan Roar', description: 'The entire arena erupts in noise simultaneously, usually after a big play.' },
 { name: 'Fan Sign', description: 'A fan holds up a visible handmade sign, regularly shown on broadcast cameras.' },
 { name: 'Bench Reaction', description: 'The broadcast cuts to the bench showing players reacting emotionally to a big play.' },
 //{ name: 'Net Caught', description: 'The net becomes tangled on the rim during play, requiring officials to stop the game and fix it before play can resume.' },
];

const rugbyItems: BingoItem[] = [
  { name: 'Try', description: 'A player grounds the ball over the try line for 5 points!' },
  { name: 'Conversion', description: 'A kick at goal after a try, worth 2 points.' },
  { name: 'Penalty Kick', description: 'A kick at goal from a penalty, worth 3 points.' },
  { name: 'Drop Goal', description: 'A drop-kick through the uprights during open play, worth 3 points.' },
  { name: 'Scrum', description: 'A set piece where forwards bind together and contest for the ball.' },
  { name: 'Lineout', description: 'The ball is thrown in from the sideline after going out of play.' },
  { name: 'Ruck', description: 'Players contest for the ball on the ground after a tackle.' },
  { name: 'Maul', description: 'A standing battle for possession where players bind together.' },
  { name: 'Tackle', description: 'A ball carrier is brought to the ground by an opponent.' },
  { name: 'Turnover', description: 'Possession changes hands at the breakdown.' },
  { name: 'Yellow Card', description: 'A player is sin-binned for 10 minutes.' },
  { name: 'Red Card', description: 'A player is sent off for the rest of the match.' },
  { name: 'Free Space', description: 'Free space - automatically marked!' },
  { name: 'Sin Bin', description: 'A player serves time off the field for foul play.' },
  { name: 'High Tackle', description: 'A dangerous tackle above the shoulders.' },
  { name: 'Offside', description: 'A player is penalized for being in an offside position.' },
  { name: 'Knock-On', description: "The ball is knocked forward by a player's hand or arm." },
  { name: 'Forward Pass', description: "An illegal pass thrown toward the opponent's goal line." },
  { name: 'Substitution', description: 'A player is replaced by a substitute.' },
  { name: 'Garryowen', description: 'A high up-and-under kick allowing forwards to charge the catcher.' },
  { name: 'Grubber Kick', description: 'A low kick along the ground through the defence.' },
  { name: 'Penalty Try', description: 'A try awarded when foul play prevented a certain score.' },
  { name: 'TMO Review', description: 'The Television Match Official reviews a decision on the big screen.' },
  { name: 'Hat Trick', description: 'A player scores three tries in one match!' },
  { name: 'Injury', description: 'A player goes down requiring medical attention.' },
];

const hockeyItems: BingoItem[] = [
  { name: 'Goal', description: 'The puck enters the net for a score!' },
  { name: 'Save', description: 'The goalie stops a shot on goal.' },
  { name: 'Penalty', description: 'A player is sent to the penalty box.' },
  { name: 'Power Play', description: 'One team has more players due to a penalty.' },
  { name: 'Hat Trick', description: 'A player scores three goals in one game!' },
  { name: 'Assist', description: 'A pass that leads to a goal.' },
  { name: 'Face-Off', description: 'The puck is dropped to start play.' },
  { name: 'Icing', description: 'The puck is shot from behind center across the goal line.' },
  { name: 'Offside', description: 'A player enters the offensive zone too early.' },
  { name: 'Breakaway', description: 'A player breaks free for a one-on-one with the goalie.' },
  { name: 'Slapshot', description: 'A powerful shot using a full backswing.' },
  { name: 'Body Check', description: 'A player uses their body to stop an opponent.' },
  { name: 'Free Space', description: 'Free space - automatically marked!' },
  { name: 'Short-Handed', description: 'Playing with fewer players than the opponent.' },
  { name: 'Overtime', description: 'Extra time to break a tie.' },
  { name: 'Empty Net', description: 'The goalie is pulled for an extra attacker.' },
  { name: 'Wrist Shot', description: 'A quick shot using wrist movement.' },
  { name: 'Deke', description: 'A fake move to get past a defender or goalie.' },
  { name: 'Rebound', description: 'A shot attempt following a saved shot.' },
  { name: 'High Stick', description: 'A penalty for hitting with a raised stick.' },
  { name: 'Wraparound', description: 'Skating behind the net and trying to score.' },
  { name: 'Glove Save', description: 'The goalie catches the puck with their glove.' },
  { name: 'Scramble', description: 'A chaotic play with many players around the puck.' },
  { name: 'Shutout', description: "The goalie doesn't allow any goals!" },
  { name: 'Fight', description: 'Players engage in a physical altercation.' },
];

const americanFootballItems: BingoItem[] = [
  { name: 'Touchdown', description: 'A player crosses the goal line to score 6 points!' },
  { name: 'Field Goal', description: 'The kicker splits the uprights for 3 points.' },
  { name: 'Interception', description: 'A defender catches a pass intended for the offense.' },
  { name: 'Fumble', description: 'A ball carrier loses possession of the football.' },
  { name: 'Sack', description: 'The quarterback is tackled behind the line of scrimmage.' },
  { name: 'Penalty Flag', description: 'A penalty flag is thrown for a rule violation.' },
  { name: 'First Down', description: 'The offense gains 10 yards and earns a new set of downs.' },
  { name: 'Extra Point', description: 'The offense kicks or runs in for 1 or 2 points after a TD.' },
  { name: 'Punt', description: 'The offense punts the ball away on fourth down.' },
  { name: 'Safety', description: 'The defense tackles the ball carrier in their own end zone for 2 points.' },
  { name: 'Two-Point Conv.', description: 'The offense runs or passes into the end zone for 2 points after a TD.' },
  { name: 'Onside Kick', description: 'A short kickoff attempt to recover the ball.' },
  { name: 'Free Space', description: 'Free space - automatically marked!' },
  { name: 'Hail Mary', description: 'A desperation long pass attempt near the end of the half or game.' },
  { name: 'Blitz', description: 'Extra defenders rush the quarterback.' },
  { name: 'Red Zone', description: "The offense has the ball inside the opponent's 20-yard line." },
  { name: 'Challenge Flag', description: 'A coach challenges an on-field ruling.' },
  { name: 'Kickoff Return', description: 'A player returns the kickoff for big yards or a touchdown.' },
  { name: 'Fake Punt', description: 'The punting team fakes the kick and runs or passes.' },
  { name: 'Screen Pass', description: 'A short pass to a receiver behind blockers.' },
  { name: 'Coin Toss', description: 'The coin toss determines who receives the opening kickoff.' },
  { name: 'Overtime', description: 'The game is tied after regulation and goes to overtime.' },
  { name: 'Snap', description: 'The center snaps the ball to begin a play.' },
  { name: 'Chant', description: 'The crowd erupts in a team chant.' },
  { name: 'Injury', description: 'A player goes down with an injury.' },
];

export function getBingoItems(sport: Sport): BingoItem[] {
  switch (sport) {
    case 'soccer':
      return soccerItems;
    case 'americanFootball':
      return americanFootballItems;
    case 'baseball':
      return baseballItems;
    case 'basketball':
      return basketballItems;
    case 'rugby':
      return rugbyItems;
    case 'hockey':
      return hockeyItems;
    default:
      return soccerItems;
  }
}
