import { Sport } from '../App';

export interface BingoItem {
  name: string;
  description: string;
  //group?: string;
}

const soccerItems: BingoItem[] = [
{ name: 'Goal', description: 'The ball fully crosses the goal line between the posts, counting as a score for the attacking team.' },
{ name: 'Corner Kick', description: 'Awarded when the defending team last touches the ball before it crosses their own goal line. The attacking team restarts' },
{ name: 'Yellow Card', description: 'A formal warning issued by the referee to a player for misconduct or a foul.' },
{ name: 'Offside', description: 'An attacking player is called for being ahead of the last defender when the ball is played to them.' },
{ name: 'Penalty', description: 'A direct free kick from the penalty spot, awarded when a foul occurs inside the defending team\'s penalty area.' },
{ name: 'Substitution', description: 'A player is removed from the match and replaced by another from the bench.' },
{ name: 'Header', description: 'A player uses their head to direct or control the ball.' },
{ name: 'Tackle', description: 'A player challenges an opponent to win possession of the ball.' },
{ name: 'Throw-In', description: 'A player throws the ball back into play from the touchline after it goes out of bounds. ⚠️ "Touchline" = "Sideline" in US/MLS.' },
{ name: 'Assist', description: 'A pass or touch that directly leads to a goal being scored.' },
{ name: 'Red Card', description: 'A player is ejected from the match for serious misconduct or receiving two yellow cards.' },
{ name: 'Free Kick', description: 'Play restarts after a foul with a kick awarded from the spot where the infraction occurred.' },
{ name: 'Cross', description: 'A player sends the ball from a wide position into the penalty area for teammates to attack.' },
{ name: 'Injury', description: 'A player goes down and requires medical attention on the pitch.' },
//{ name: 'Hat Trick', description: 'One player scores three goals in a single match.' },
{ name: 'Volley', description: 'A player strikes the ball out of the air before it touches the ground.' },
{ name: 'Nutmeg', description: 'A player passes the ball through an opponent\'s legs to get past them.' },
{ name: 'Clean Sheet', description: 'The goalkeeper and defense prevent the opposing team from scoring for the entire match.' },
{ name: 'Own Goal', description: 'A player accidentally scores into their own net, giving the opposing team a point.' },
{ name: 'VAR Check', description: 'The Video Assistant Referee reviews a decision made on the pitch, causing a pause in play.' },
{ name: 'Stadium Wave', description: 'Fans stand and raise their arms in sequence around the stadium, creating a ripple effect. ⚠️ "Stadium Wave" = "Mexican Wave" in UK/international football.' },
{ name: 'Face/ Body Paint', description: 'A fan paints their face or body in team colors to show support.' },
{ name: 'Flag Waving', description: 'A fan waves a large team or national flag in the stands.' },
//{ name: 'Flares/ Smoke', description: 'Colored smoke or flares set off by fans, usually to celebrate or intimidate. ⚠️ Specific to UK/European football.' },
{ name: 'Drum Beat', description: 'A fan section keeps a steady beat on drums to rally the crowd.' },
{ name: 'Retro Jersey', description: 'A fan wears a classic jersey from a past era of the club. ⚠️ "Jersey" = "Kit" in UK/international football.' },
{ name: 'Fan Hug', description: 'Two or more fans embrace in the stands, usually after a goal.' },
{ name: 'Team Scarf', description: 'A supporter holds or wears the club\'s official scarf. ⚠️ Specific to UK/European football.' },
//{ name: 'Fan Tears', description: 'A fan is visibly crying, from joy or heartbreak.' },
{ name: 'Banner', description: 'A large sign or cloth displayed by fans with a message or club crest.' },
//{ name: 'Fan Dance', description: 'Fans break into a coordinated or spontaneous dance in the stands.' },
{ name: 'Crowd Roar', description: 'The entire stadium erupts in noise simultaneously.' },
{ name: 'Security Check', description: 'Stadium staff checks a fan or intervenes in the stands.' },
{ name: 'Kickoff', description: 'The match begins or restarts with a player passing the ball from the center circle.' },
{ name: 'Goal Celebration', description: 'Players celebrate together immediately after scoring.' },
{ name: 'Manager Yelling', description: 'Manager shouts instructions or protests from the touchline. ⚠️ "Manager" = "Coach/Head Coach" in US/MLS. ⚠️ "Touchline" = "Sideline" in US/MLS.' },
{ name: 'Missed Shot', description: 'A player shoots and the ball goes wide, over, or straight at the keeper.' },
{ name: 'Extra Time', description: 'Two additional 15-minute periods played when the match is tied after 90 minutes.' },
{ name: 'Penalty Shootout', description: 'Teams alternate penalty kicks to decide the winner after a drawn match.' },
{ name: 'Slide Tackle', description: 'A player slides along the ground to dispossess an opponent.' },
{ name: 'Knee Slide', description: 'A player celebrates a goal by sliding on their knees across the pitch.' },
{ name: 'Shirt Pull', description: 'A player grabs an opponent\'s jersey, typically to slow them down.' },
{ name: 'Push Foul', description: 'A player shoves an opponent, resulting in a free kick.' },
{ name: 'Bad Tackle', description: 'A dangerous or reckless challenge that endangers the opponent.' },
{ name: 'Clean Tackle', description: 'A perfectly timed challenge that wins the ball without fouling.' },
{ name: 'Header Goal', description: 'A player scores by directing the ball into the net with their head.' },
{ name: 'Manager Yellow Card', description: 'The referee books the manager for misconduct on the touchline. ⚠️ "Manager" = "Coach/Head Coach" in US/MLS. ⚠️ "Touchline" = "Sideline" in US/MLS.' },
{ name: 'Manager Red Card', description: 'The manager is sent to the stands for serious or repeated misconduct. ⚠️ "Manager" = "Coach/Head Coach" in US/MLS. ' },
{ name: 'Injury Tackle', description: 'A tackle that results in a player going down injured.' },
{ name: 'Ball Into Seats', description: 'The ball is kicked or deflected out of play and into the crowd.' },
{ name: 'Missed Pass', description: 'A pass that fails to reach its intended teammate.' },
{ name: 'Ref Bad Call', description: 'The referee makes a decision that players or fans strongly disagree with.' },
{ name: 'Goal Disallowed', description: 'A goal is ruled out, usually for offside or a foul in the buildup.' },
{ name: 'Keeper Save', description: 'The goalkeeper stops a shot from going into the net.' },
{ name: 'Goal Kick', description: 'A player from the defending team kicks the ball back into play after it crosses the goal line, last touched by an attacking player.' },
{ name: 'Double Substitution', description: 'A manager makes two player changes at the same time.' },
{ name: 'Triple Substitution', description: 'A manager makes three player changes simultaneously.' },
{ name: 'Collision Injury', description: 'Physical damage resulting from direct, high-force impact with another player, the ground, or equipment.' },
{ name: 'Post/ Crossbar Hit', description: 'A shot strikes the upright or crossbar and stays out of the net.' },
{ name: 'Brace', description: 'One player scores two goals in the same match.' },
{ name: 'Stoppage Time Goal', description: 'A goal scored after the 90th minute during injury time added by the referee.' },
{ name: 'Diving/ Simulation', description: 'A player deliberately falls to the ground to deceive the referee into awarding a foul.' },
{ name: 'Long Range Goal', description: 'A goal scored from outside the penalty area, typically 25 yards or more.' },
{ name: 'Offside Trap', description: 'The defensive line steps up simultaneously to catch an attacker offside.' },
{ name: 'Tactical Foul', description: 'A deliberate foul to stop a dangerous counterattack, often resulting in a yellow card.' },
{ name: 'Time Wasting', description: 'A player deliberately delays the game, usually prompting a booking or crowd reaction.' },
{ name: 'Shirt Swap', description: 'Two opposing players exchange jerseys at the end of the match.' },
{ name: 'Wall Jump', description: 'During a free kick, one or more defenders in the wall leap to block a low shot.' },
//{ name: 'Bicycle Kick', description: 'A player kicks the ball backwards over their own head while airborne, typically as a shot on goal.' },
{ name: 'Backheel Pass', description: 'A player passes the ball backwards using their heel.' },
{ name: 'National Flag', description: 'A country\'s official flag displayed or worn by supporters. ⚠️ Specific to international matches and World Cup.' },
{ name: 'Fan Song', description: 'Supporters sing a recognizable song or rallying anthem together as a group. ⚠️ "Fan Song" = "Terrace Song" in UK.' },
{ name: '5th Sub Used', description: 'The manager uses their fifth and final substitution of the match.' },
{ name: 'Team Anthem', description: 'The official team or national anthem is played, with fans singing along.' },
{ name: 'Ole Chant', description: 'The crowd chants "Ole!" in rhythm each time their team completes a series of passes, signaling dominance. ⚠️ Specific to UK/European and South American football.' },
//{ name: 'Streaker', description: 'An unclothed person runs across the pitch during the match.' },
//{ name: 'Pitch Invasion', description: 'A fan or fans enter the playing field during or after the match.' },
//{ name: 'Goalkeeper Goal', description: 'The goalkeeper scores a goal, either from open play or a direct kick.' },
//{ name: 'Rabona', description: 'A player wraps their kicking foot behind their standing leg to strike the ball.' },
//{ name: 'Panenka Penalty', description: 'A penalty taken with a soft chip down the center of the goal while the keeper dives to one side.' },
//{ name: 'Water Break', description: 'Play is temporarily stopped for players to hydrate, common in hot weather matches.' },
//{ name: 'Vuvuzela', description: 'A plastic horn blown by fans, famous from the 2010 World Cup in South Africa. ⚠️ Specific to African football and World Cup' },
//{ name: 'Ref Protest Sign', description: 'A fan in the stands holds up a visible sign directed at the referee, expressing disagreement with calls made during' },
];

const baseballItems: BingoItem[] = [
 { name: 'Home Run', description: 'A batter hits the ball out of the park, automatically scoring all runners on base including themselves.' },
 { name: 'Strikeout', description: 'A batter receives three strikes and is out, either by swinging and missing or a called third strike.' },
 { name: 'Double Play', description: 'The defense records two outs on a single play, typically a ground ball fielded and thrown to first and second.' },
 { name: 'Walk', description: 'A batter receives four balls and advances to first base without the ball being put in play.' },
 { name: 'Stolen Base', description: 'A baserunner advances to the next base while the pitcher is delivering the ball, without a hit.' },
 { name: 'Fly Out', description: 'A batter hits the ball high into the air and it is caught by a fielder before touching the ground.' },
 { name: 'Ground Out', description: 'A batter hits the ball along the ground and is thrown out at first base.' },
 { name: 'Hit by Pitch', description: 'A batter is struck by a pitched ball and awarded first base.' },
 { name: 'Bunt', description: 'A batter intentionally taps the ball lightly into the infield instead of taking a full swing.' },
 { name: 'Error', description: 'A fielder mishandles a ball in a way that allows a batter or runner to advance when they otherwise would not have.' },
 { name: 'Sacrifice Fly', description: 'A batter hits a fly ball that is caught for an out, but is deep enough to allow a runner to tag up and score.' },
 { name: 'Foul Ball', description: 'A batted ball lands outside the foul lines, counting as a strike unless the batter already has two strikes.' },
 { name: 'Pitching Change', description: 'The manager removes the current pitcher and brings in a new one from the bullpen.' },
 { name: 'Wild Pitch', description: 'A pitcher throws a ball so far outside the strike zone that the catcher cannot control it, allowing runners to advance.' },
 //{ name: 'Grand Slam', description: 'A home run hit with the bases loaded, scoring four runs at once.' },
 { name: 'Caught Stealing', description: 'A baserunner attempts to steal a base but is thrown out by the catcher.' },
 { name: 'Infield Hit', description: 'A batter reaches base safely on a ball that never leaves the infield.' },
 { name: 'Balk', description: 'The pitcher makes an illegal motion on the mound, advancing all baserunners one base.' },
 { name: 'Diving Catch', description: 'A fielder throws themselves to the ground to catch a ball that would otherwise fall for a hit.' },
 { name: 'RBI', description: 'A batter\'s hit or play directly causes a run to score.' },
 { name: 'Called Strike', description: 'The umpire calls a strike on a pitch the batter did not swing at.' },
 { name: 'Single', description: 'A batter hits the ball and reaches first base safely.' },
 { name: 'Double', description: 'A batter hits the ball and reaches second base safely.' },
 { name: 'Triple', description: 'A batter hits the ball and reaches third base safely.' },
 { name: 'Pickoff', description: 'The pitcher throws to a base in an attempt to tag out a baserunner who has strayed too far.' },
 { name: 'Sacrifice Bunt', description: 'A batter intentionally bunts to advance a runner, accepting an out in exchange.' },
 { name: 'Relief Pitcher', description: 'A pitcher who enters the game to replace the starting pitcher.' },
 { name: 'Umpire Call', description: 'The umpire makes a visible call on the field, such as safe, out, or ball and strike.' },
 { name: 'Line Drive', description: 'A batter hits the ball sharply and directly, traveling in a nearly straight line.' },
 { name: 'Tag Out', description: 'A fielder tags a runner with the ball while the runner is off base.' },
 { name: 'Strikeout Looking', description: 'A batter is called out on a third strike without swinging, often drawing a strong crowd reaction.' },
 //{ name: 'Walk-Off Hit', description: 'A hit in the bottom of the final inning that ends the game with a win for the home team.' },
 { name: 'Hit and Run', description: 'The baserunner starts running as the pitcher delivers, and the batter swings to protect them.' },
 { name: 'Intentional Walk', description: 'The pitcher deliberately throws four balls to avoid pitching to a dangerous batter.' },
 { name: 'Manager Ejection', description: 'The manager is thrown out of the game by the umpire, often after arguing a call.' },
 { name: 'Umpire Argument', description: 'A player or manager charges onto the field to argue a call with the umpire.' },
 { name: 'Replay Review', description: 'The umpires review a disputed call using video replay technology.' },
 //{ name: 'Extra Innings', description: 'The game is tied after nine innings and continues until a winner is decided.' },
 { name: 'Bases Loaded', description: 'All three bases are occupied by runners simultaneously.' },
 { name: 'Leadoff Home Run', description: 'The first batter of an inning hits a home run.' },
 { name: 'Passed Ball', description: 'The catcher fails to control a pitch they should have caught, allowing a baserunner to advance.' },
 { name: 'ABS Challenge', description: 'A batter or manager challenges an umpire\'s ball or strike call, triggering an automated review system that can overturn the decision.' },
 { name: 'Pitch Clock Violation', description: 'The pitcher or batter exceeds the time limit between pitches, resulting in an automatic ball or strike called against them.' },
 { name: 'Mound Visit', description: 'The manager or pitching coach walks to the mound to talk to the pitcher, pausing play.' },
 { name: 'Pinch Hitter', description: 'A substitute batter enters the game to hit in place of another player, usually for a strategic advantage.' },
 { name: 'Base Coach Interaction', description: 'A base coach visibly signals or talks to a runner, directing their next move on the basepaths.' },
 { name: 'Celebrity in the Stands', description: 'The broadcast cuts to a recognizable celebrity watching the game from the stands.' },
 { name: 'First Hit of the Game', description: 'The first batter to reach base safely on a hit, a notable milestone early in the game.' },
 { name: 'First Run of the Game', description: 'The first run scored by either team, often a turning point in momentum.' },
 { name: 'Bullpen Warmup', description: 'The broadcast shows a relief pitcher warming up in the bullpen before being called into the game.' },
 { name: 'Designated Hitter', description: 'The player who bats in place of the pitcher in the lineup without playing a defensive position in the field.' },
 { name: 'Broken Bat', description: 'A pitcher\'s pitch causes the batter\'s bat to crack or shatter on contact, sending pieces of the bat onto the field.' },
 { name: 'Rundown', description: 'A baserunner is caught between two bases with fielders chasing them back and forth in an attempt to make a tag.' },
 { name: 'Slide Into Home', description: 'A baserunner slides feet-first or head-first into home plate to score a run, often under a throw from the outfield.' },
 { name: '3 Up 3 Down', description: 'A pitcher retires all three batters in an inning in order without allowing anyone to reach base.' },
 { name: 'Foul Tip', description: 'The ball barely grazes the edge of the bat and travels directly into the catcher\'s mitt, counting as a strike.' },
 { name: 'Pop Fly', description: 'A batter hits the ball high into the air in the infield or shallow outfield, typically resulting in an easy out for the fielder positioned underneath it.' },
 { name: 'Hot Dog', description: 'A fan is eating a hot dog, the iconic ballpark food.' },
 { name: 'Beer Cup', description: 'A fan is seen with a beer, a staple of the ballpark experience.' },
 { name: 'Cracker Jack', description: 'A fan is seen with the iconic caramel popcorn and peanut snack, immortalized in Take Me Out to the Ballgame.' },
 { name: '7th Inning Stretch', description: 'The crowd stands and sings Take Me Out to the Ballgame between the top and bottom of the seventh inning.' },
 { name: 'Organ Music', description: 'The stadium organ plays between plays or during stoppages, a tradition dating back to the 1940s.' },
 { name: 'National Anthem', description: 'The national anthem is performed before the game begins with fans standing and removing their hats.' },
 { name: 'Stadium Wave', description: 'Fans stand and raise their arms in sequence around the stadium, creating a ripple effect.' },
 { name: 'Face Paint', description: 'A fan has painted their face in team colors.' },
 { name: 'Painted Chest', description: 'A fan has painted their torso in team colors.' },
 { name: 'Retro Jersey', description: 'A fan wears a classic jersey from a past era of the team.' },
 //{ name: 'Colorful Wig', description: 'A fan wears a brightly colored wig in team colors.' },
 //{ name: 'Big Hat', description: 'A fan wearing an oversized or novelty hat in team colors.' },
 { name: 'Banner', description: 'A large sign or cloth displayed by fans with a message or team logo.' },
 { name: 'Fan Roar', description: 'The entire stadium erupts in noise simultaneously.' },
 { name: 'High Five', description: 'Fans high five each other in the stands, usually after a big play.' },
 { name: 'Charge Cheer', description: 'The crowd responds to the Charge bugle call in unison.' },
 { name: 'Souvenir Ball Catch', description: 'A fan catches a foul ball or home run ball as a keepsake.' },
 { name: 'Mascot On Field', description: 'The team mascot appears on the field or interacts with fans during a stoppage in play.' },
 //{ name: 'Perfect Game', description: 'A pitcher retires all 27 batters faced without allowing any baserunner. Only 24 have occurred in MLB history.' },
 //{ name: 'No-Hitter', description: 'A pitcher completes a game without allowing any hits, one of the rarest individual achievements in baseball.' },
 //{ name: 'Triple Play', description: 'The defense records three outs on a single play, one of the most exciting and rare defensive moments in baseball.' },
];

const basketballItems: BingoItem[] = [
 { name: 'Three-Pointer', description: 'A shot made from beyond the arc, worth three points instead of two.' },
 { name: 'Dunk', description: 'A player jumps and forcefully pushes the ball through the basket with one or both hands.' },
 { name: 'Block', description: 'A defensive player legally deflects a shot attempt, preventing it from reaching the basket.' },
 { name: 'Steal', description: 'A defensive player takes the ball away from an offensive player, causing a turnover.' },
 { name: 'Assist', description: 'A pass that directly leads to a made basket by a teammate.' },
 { name: 'Rebound', description: 'A player grabs the ball after a missed shot, either on offense or defense.' },
 { name: 'Free Throw', description: 'An uncontested shot from the free throw line, awarded after certain fouls.' },
 { name: 'Foul', description: 'Illegal physical contact by one player against another, stopping play.' },
 { name: 'Timeout', description: 'A team stops play to huddle with the coach and discuss strategy.' },
 { name: 'Turnover', description: 'A team loses possession of the ball without taking a shot.' },
 { name: 'Alley-Oop', description: 'One player throws a lob pass near the basket and a teammate catches it in the air and dunks or lays it in.' },
 { name: 'Layup', description: 'A close-range shot where a player rolls the ball off the backboard or drops it over the rim.' },
 { name: 'Double-Double', description: 'A player reaches double digits in two statistical categories in the same game, most commonly points and rebounds.' },
 { name: 'Fast Break', description: 'A team pushes the ball up the court quickly before the defense can set up, creating an easy scoring opportunity.' },
 { name: 'Jump Ball', description: 'Two opposing players contest for the ball held by a referee, who tosses it up between them.' },
 { name: 'Technical Foul', description: 'A foul called for unsportsmanlike conduct, arguing with officials, or a rules violation not involving contact.' },
 //{ name: 'Buzzer Beater', description: 'A shot made just as the game clock expires, often deciding the outcome.' },
 { name: 'Crossover', description: 'A ball handler quickly switches the ball from one hand to the other to change direction and lose a defender.' },
 { name: 'And-One', description: 'A player is fouled while making a basket, earning one additional free throw attempt.' },
 //{ name: 'Triple-Double', description: 'A player reaches double digits in three statistical categories in the same game.' },
 { name: 'Traveling', description: 'A player takes too many steps without dribbling, resulting in a turnover.' },
 { name: 'Charge', description: 'A defensive player plants their feet and absorbs contact from an offensive player, drawing an offensive foul.' },
 { name: 'Substitution', description: 'A player on the bench enters the game to replace a player on the court.' },
 { name: 'Bank Shot', description: 'A shot that bounces off the backboard before going into the basket.' },
 { name: 'Double Dribble', description: 'A player dribbles the ball, stops, and then dribbles again, resulting in a turnover.' },
 { name: 'Shot Clock Violation', description: 'A team fails to attempt a shot within the allotted time, resulting in a turnover.' },
 { name: 'Injury', description: 'A player goes down and requires medical attention, stopping play.' },
 { name: 'Coach Yelling', description: 'The head coach shouts instructions or protests a call from the sideline.' },
 { name: 'Tip Off', description: 'The game begins with a jump ball at center court between two opposing players.' },
 { name: 'Missed Free Throw', description: 'A player fails to convert a free throw attempt, drawing a crowd reaction.' },
 { name: 'Air Ball', description: 'A shot attempt that misses the rim, backboard, and net entirely, drawing a loud crowd reaction.' },
 { name: 'Flagrant Foul', description: 'A hard or reckless foul deemed dangerous by the referee, resulting in free throws and possession for the opposing team.' },
 { name: 'Intentional Foul', description: 'A deliberate foul used as a late-game strategy to stop the clock and send the opposing team to the free throw line.' },
 //{ name: 'Overtime', description: 'The game is tied at the end of regulation and continues with additional five-minute periods until a winner is determined.' },
 //{ name: 'Ejection', description: 'A player or coach is removed from the game after receiving two technical fouls.' },
 { name: 'Poster Dunk', description: 'A powerful dunk where the offensive player dunks directly over a defender.' },
 { name: 'Ankle Breaker', description: 'A crossover or dribble move so sharp that the defender loses their footing and falls.' },
 { name: 'Half Court Shot', description: 'A shot attempted from half court, usually at the end of a quarter, generating a massive crowd reaction if it goes in.' },
 { name: 'Tip-In', description: 'A player taps a missed shot directly into the basket off the rebound without fully controlling the ball first.' },
 { name: 'No-Look Pass', description: 'A pass made without looking at the intended receiver, designed to fool the defense.' },
 { name: 'Pick and Roll', description: 'A play where one player sets a screen for the ball handler, then rolls toward the basket to receive a pass.' },
 { name: 'Hook Shot', description: 'A one-handed shot where the player sweeps their arm in an arc over their head to release the ball.' },
 { name: 'Fadeaway', description: 'A jump shot taken while leaning away from the defender, making it nearly impossible to block.' },
 { name: 'Mid-Range Jumper', description: 'A jump shot taken from between the paint and the three-point line.' },
 { name: 'Coach Challenge', description: 'A coach uses their one challenge to request a referee review a specific call via video replay.' },
 { name: 'Official Review', description: 'Referees initiate their own video review, typically in the last two minutes of the game for out of bounds, shot clock, or flagrant foul calls.' },
 { name: 'Intentional Miss', description: 'A player deliberately misses a free throw to allow a teammate to grab the rebound, used as a late-game strategy.' },
 { name: 'Foul Trouble', description: 'A player has accumulated enough fouls that the coach benches them to protect them from fouling out.' },
 { name: 'Towel Twirl', description: 'A player on the bench or a fan twirls a towel overhead to energize the crowd or celebrate a big play.' },
 { name: 'Full Court Pass', description: 'A player throws the ball the length of the court, usually to a teammate on a fast break or to beat the shot clock.' },
 { name: 'Loose Ball', description: 'Neither team has possession and both scramble to recover the ball, generating a crowd reaction.' },
 { name: 'Charge Drawn', description: 'A defensive player plants their feet and takes a hard hit from an offensive player, drawing an offensive foul through sheer hustle.' },
 { name: 'Box Out', description: 'A player uses their body to block an opponent from getting position for a rebound.' },
 { name: 'Corner Three', description: 'A three-pointer taken from the corner of the court, the most efficient shot in basketball.' },
 { name: 'Flop', description: 'A player dramatically falls or reacts to minimal contact to deceive the referee into calling a foul.' },
 { name: 'Face Paint', description: 'A fan has painted their face in team colors, often highlighted by broadcast cameras.' },
 { name: 'Colorful Wig', description: 'A fan wears a brightly colored wig in team colors, regularly sought out by broadcast cameras.' },
 { name: 'Banner', description: 'A large sign or cloth displayed by fans with a message or team slogan.' },
 { name: 'Mascot On Court', description: 'The team mascot appears on the court during a timeout or stoppage, interacting with fans or performing.' },
 { name: 'Half-Time Show', description: 'Performers, acrobats, or entertainers take the court during halftime.' },
 { name: 'Dance Cam', description: 'The jumbotron highlights a fan dancing energetically in the stands.' },
 { name: 'Celebrity Courtside', description: 'The broadcast cuts to a recognizable celebrity sitting courtside at the game.' },
 { name: 'Player Introductions', description: 'The starting lineup is announced with arena lights, music, and video before tip off.' },
 { name: 'Timeout Performance', description: 'Dancers, acrobats, or other entertainers perform on the court during a timeout stoppage.' },
 { name: 'Courtside Selfie', description: 'A fan sitting courtside is shown taking a selfie, often capturing players or the court in the background.' },
 { name: 'Defense Chant', description: 'The crowd chants "Defense!" in unison, clapping in rhythm to pressure the opposing team.' },
 { name: 'Fan Roar', description: 'The entire arena erupts in noise simultaneously, usually after a big play.' },
 { name: 'Fan Sign', description: 'A fan holds up a visible handmade sign, regularly shown on broadcast cameras.' },
 { name: 'Bench Reaction', description: 'The broadcast cuts to the bench showing players reacting emotionally to a big play.' },
//{ name: 'Net Caught', description: 'The net becomes tangled on the rim during play, requiring officials to stop the game and fix it before play can resume.' },
];

const rugbyItems: BingoItem[] = [
 { name: 'Try', description: 'A player grounds the ball over the try line, scoring five points for their team.' },
 { name: 'Conversion', description: 'A kick at goal taken after a try, worth two additional points if successful.' },
 { name: 'Penalty Kick', description: 'A kick at goal awarded after an infringement by the opposing team, worth three points.' },
 { name: 'Drop Goal', description: 'A player drops the ball and kicks it through the uprights during open play, worth three points.' },
 { name: 'Scrum', description: 'Eight forwards from each team bind together and contest for the ball in a pushing contest.' },
 { name: 'Lineout', description: 'The ball is thrown in from the touchline after going out of play, with players lifting teammates to contest the catch.' },
 { name: 'Ruck', description: 'Players from both teams bind over the ball on the ground after a tackle to contest possession.' },
 { name: 'Maul', description: 'A standing battle for possession where the ball carrier is held and teammates bind around them.' },
 { name: 'Tackle', description: 'A ball carrier is brought to the ground by an opponent, requiring them to release the ball immediately.' },
 { name: 'Turnover', description: 'Possession changes hands at the breakdown, either through a penalty or a legal steal.' },
 { name: 'Yellow Card', description: 'A player is shown a yellow card and sent to the sin bin for ten minutes, leaving their team temporarily shorthanded.' },
 //{ name: 'Red Card', description: 'A player is sent off for the remainder of the match for serious foul play.' },
 //{ name: '20-Minute Red Card', description: 'A player is shown a red card but their team can replace them after twenty minutes, used for technical offences rather than deliberate dangerous play.' },
 { name: 'High Tackle', description: 'A tackle made above the shoulders, one of the most penalised and reviewed offences in modern rugby.' },
 { name: 'Offside', description: 'A player is penalised for being in an illegal position, one of the most common infringements in rugby.' },
 { name: 'Knock-On', description: 'The ball is knocked forward from a player\'s hand or arm, resulting in a scrum to the opposing team.' },
 { name: 'Forward Pass', description: 'A pass thrown toward the opponent\'s try line rather than laterally or backward, resulting in a scrum.' },
 { name: 'Substitution', description: 'A player is replaced by a substitute from the bench.' },
 { name: 'Garryowen', description: 'A high kick launched into the air allowing forwards to charge the catcher under pressure. ⚠️ "Garryowen" = "Up-and-Under" in UK' },
 { name: 'Grubber Kick', description: 'A low kick along the ground through the defence, designed for a player to chase and gather behind the defensive line.' },
 //{ name: 'Penalty Try', description: 'A try awarded by the referee when foul play prevented what would have been a certain score.' },
 { name: 'TMO Review', description: 'The Television Match Official reviews a decision on the big screen, pausing play to ensure the correct call is made.' },
 //{ name: 'Hat Trick', description: 'One player scores three tries in a single match.' },
 { name: 'Injury', description: 'A player goes down requiring medical attention, stopping play.' },
 { name: 'Kickoff', description: 'A team kicks the ball from the halfway line to start each half and restart play after a score.' },
 { name: 'Free Kick', description: 'A kick awarded to the non-offending team for a minor infringement, used to restart play but cannot be kicked directly at goal.' },
 { name: 'Restart', description: 'The ball is kicked back into play after a score or the ball goes dead, restarting the match.' },
 { name: 'Kick to Touch', description: 'A player kicks the ball out of bounds intentionally to gain territory and stop play. ' },
 { name: 'Kick Return', description: 'A player catches a kick and runs it back toward the opposing try line.' },
 { name: 'Double Substitution', description: 'Two player substitutions are made at the same time.' },
 { name: 'Triple Substitution', description: 'Three player substitutions are made simultaneously, a common tactical move in rugby.' },
 { name: 'Advantage', description: 'The referee signals advantage and allows play to continue after an infringement, giving the non-offending team a chance to benefit before stopping play.' },
 { name: 'Quick Tap', description: 'Instead of kicking for goal from a penalty, a player taps the ball with their foot and immediately runs, restarting play quickly.' },
 { name: 'Line Break', description: 'An attacking player breaks through the defensive line into open space, generating a major crowd reaction.' },
 { name: 'Offload', description: 'A player passes the ball to a teammate while being tackled, before hitting the ground, keeping the attack alive.' },
 { name: 'Dummy Pass', description: 'A player fakes a pass to deceive defenders before continuing to run with the ball.' },
 { name: 'Charge Down', description: 'A defender blocks a kick with their body or hands at the moment it is kicked, potentially winning possession.' },
 { name: 'Blood Sub', description: 'A player is temporarily replaced due to a visible bleeding injury and is permitted to return after receiving treatment.' },
 { name: '50:22 Kick', description: 'A player kicks from inside their own half and the ball bounces in the field before going into touch inside the opponent\'s 22-metre area, rewarding the kicking team with the lineout throw.' },
 { name: 'Box Kick', description: 'The scrum half kicks the ball high from the base of the scrum or ruck, designed for the kicking team to contest the catch.' },
 { name: 'Chip Kick', description: 'A short kick over the defence for a player to chase and gather behind the defensive line.' },
 { name: 'Crash Ball', description: 'A forward runs directly and hard into defenders to gain ground, used to tire the defence and create space.' },
 { name: 'Scrum Collapse', description: 'The scrum falls to the ground before the ball is won, requiring the referee to reset and restart the scrum.' },
 { name: 'Lineout Steal', description: 'The defending team wins the lineout throw instead of the team that threw it in, a significant tactical moment.' },
 //{ name: 'Interception Try', description: 'A defender catches a pass intended for an attacker and runs the length of the field to score.' },
 { name: 'Drop Goal Attempt', description: 'A player attempts a drop goal during open play but misses, generating a crowd reaction.' },
 { name: 'Ball Kicked Out on the Full', description: 'A kick goes directly into touch without bouncing in the field of play, giving the lineout throw back to the opposing team.' },
 { name: 'Referee Calls Captains Over', description: 'The referee stops play to speak directly with both captains, usually to issue a formal warning to one or both teams.' },
 { name: 'First Try Scorer', description: 'The player who scores the opening try of the match, a closely watched and heavily anticipated moment.' },
 { name: 'Man of the Match', description: 'The best player of the game is announced and celebrated after the final whistle.' },
 { name: 'Penalty Missed', description: 'A penalty kick fails to go through the uprights, often generating a loud crowd reaction from both sets of supporters.' },
 { name: 'Driving Maul Try', description: 'A try scored directly from an unstoppable driving maul where forwards carry the ball over the try line bound together.' },
 { name: 'Hands in the Ruck', description: 'A player illegally uses their hands to interfere with the ball while it is in a ruck, resulting in a penalty.' },
 { name: 'Not Releasing', description: 'A tackled player fails to immediately release the ball after being brought to the ground, resulting in a penalty.' },
 { name: 'Tackler Not Rolling Away', description: 'A tackler fails to roll away from the tackled player after making the tackle, preventing the ruck from forming legally and resulting in a penalty.' },
 { name: 'Missed Conversion', description: 'A conversion kick fails to pass between the uprights after a try is scored, generating a crowd reaction from both sets of supporters.' },
 { name: 'Fend', description: 'A ball carrier extends their arm to push off a would-be tackler and stay on their feet, keeping the attack alive.' },
 { name: 'Obstruction', description: 'A player illegally gets in the path of an opponent who does not have the ball, preventing them from making a play, resulting in a penalty.' },
 { name: 'Face Paint Stripes', description: 'A fan has painted stripes on their face in team colors.' },
 { name: 'Flag Waving', description: 'A fan waves a large team or national flag in the stands.' },
 { name: 'Pub Singing', description: 'Fans sing team songs and anthems together in the pub before or after the match.' },
 //{ name: 'Beer Cup', description: 'A fan is seen with a beer, a staple of the rugby match day experience.' },
 { name: 'Fan Roar', description: 'The entire stadium erupts in noise simultaneously, usually after a try or a big defensive stop.' },
 { name: 'Retro Jersey', description: 'A fan wears a classic jersey from a past era of the club or national team.' },
 { name: 'Team Scarf', description: 'A fan wears or holds the team\'s official scarf in the stands.' },
 { name: 'Painted Chest', description: 'A fan has painted their torso in team colors.' },
 { name: 'Banner', description: 'A large sign or cloth displayed by fans with a message or team slogan.' },
 { name: 'Big Hat', description: 'A fan wears an oversized or novelty hat in team colors.' },
 //{ name: 'Colorful Wig', description: 'A fan wears a brightly colored wig in team colors.' },
 { name: 'Drum Beat', description: 'A fan section keeps a steady beat on drums to energize the crowd.' },
 { name: 'Ref Protest Chant', description: 'The crowd chants in unison to protest a referee\'s decision.' },
 { name: 'Jersey Swap', description: 'Players from opposing teams exchange jerseys at the end of the match as a sign of mutual respect.' },
 { name: 'Muddy Jersey', description: 'A player\'s jersey is visibly covered in mud, reflecting the physical nature of the game played in all weather conditions.' },
 { name: 'Stadium Anthem', description: 'The crowd sings the team\'s signature anthem together, such as Swing Low Sweet Chariot for England or Bread of Heaven for Wales.' },
 { name: 'National Anthem', description: 'The national anthem is performed before an international match.' },
 { name: 'Crowd Sings During Play', description: 'The crowd breaks into a spontaneous song or chant while play continues on the pitch.' },
 //{ name: 'Nil Score', description: 'A team fails to score any points for the entire match.' },
 //{ name: 'Haka', description: 'The New Zealand All Blacks perform their traditional Māori challenge before international matches. ⚠️ Specific to New Zealand.' },
 //{ name: 'Hot Pie', description: 'A fan is eating a hot meat pie, the iconic stadium food at British and New Zealand rugby grounds. ⚠️ Specific to UK and New Zealand.' },
];

const hockeyItems: BingoItem[] = [
 { name: 'Goal', description: 'The puck fully crosses the goal line between the posts, scoring one point for the attacking team.' },
 { name: 'Save', description: 'The goaltender stops a shot from crossing the goal line.' },
 { name: 'Penalty', description: 'A player violates the rules and is sent to the penalty box, leaving their team shorthanded. ⚠️ "Penalty Box" = "Sin Bin" in some European hockey coverage.' },
 { name: 'Power Play', description: 'A team has a numerical advantage on the ice because the opposing team has a player in the penalty box.' },
 //{ name: 'Hat Trick', description: 'One player scores three goals in a single game.' },
 { name: 'Assist', description: 'A pass or play that directly leads to a goal being scored.' },
 { name: 'Face-Off', description: 'Two players compete for the puck after the referee drops it between them to restart play.' },
 { name: 'Icing', description: 'A player shoots the puck from behind the center line all the way past the opposing goal line without it being touched, stopping play.' },
 { name: 'Offside', description: 'An attacking player enters the offensive zone before the puck, stopping play.' },
 { name: 'Breakaway', description: 'A player gets past all defenders and skates in alone on the goaltender.' },
 { name: 'Slapshot', description: 'A player winds up and strikes the puck hard with a full swing of the stick.' },
 { name: 'Body Check', description: 'A player uses their body to legally hit an opponent who has the puck.' },
 { name: 'Short-Handed', description: 'A team scores a goal while playing with fewer skaters due to a penalty.' },
 { name: 'Overtime', description: 'The game is tied after three periods and continues with sudden death play until a goal is scored.' },
 { name: 'Empty Net', description: 'The goalie is pulled for an extra attacker, leaving the net unguarded.' },
 { name: 'Wrist Shot', description: 'A player snaps the puck quickly off their stick using wrist motion rather than a full swing.' },
 { name: 'Deke', description: 'A player uses a move or fake to get past a defender or goaltender.' },
 { name: 'Rebound', description: 'The puck bounces back from the goaltender or post, creating a second scoring chance.' },
 { name: 'High Stick', description: 'A player\'s stick makes contact with an opponent above shoulder height, resulting in a penalty.' },
 { name: 'Wraparound', description: 'A player skates around the back of the net and attempts to tuck the puck in from the other side.' },
 { name: 'Glove Save', description: 'The goaltender catches the puck cleanly in their glove.' },
 { name: 'Scramble', description: 'A chaotic battle for the puck in front of the net with multiple players involved.' },
 { name: 'Shutout', description: 'The goaltender prevents the opposing team from scoring for the entire game.' },
 //{ name: 'Fight', description: 'Two players drop their gloves and exchange punches, both receiving five-minute major penalties.' },
 { name: 'Puck Drop', description: 'The ceremonial opening face-off to start the game, often involving a celebrity or dignitary.' },
 //{ name: 'Shootout', description: 'After a tied overtime period in the regular season, teams alternate penalty shots to determine a winner.' },
 { name: 'Block Shot', description: 'A defender sacrifices their body to block a shot before it reaches the goaltender.' },
 { name: 'Line Change', description: 'Players on the ice are substituted for fresh players from the bench, often on the fly during play.' },
 { name: 'Dump and Chase', description: 'A team shoots the puck into the offensive zone and chases it down rather than carrying it in.' },
 { name: 'Turnover', description: 'A team loses possession of the puck without taking a shot, giving the opposing team the puck.' },
 { name: 'Slashing', description: 'A player strikes an opponent with their stick, resulting in a penalty.' },
 { name: 'Hooking', description: 'A player uses their stick to hook or restrain an opponent, resulting in a penalty.' },
 { name: 'Tripping', description: 'A player uses their stick or leg to trip an opponent, resulting in a penalty.' },
 { name: 'Cross-Check', description: 'A player delivers a check with both hands on the stick shaft extended between them, resulting in a penalty.' },
 { name: 'Boarding', description: 'A player violently checks an opponent into the boards, resulting in a major penalty.' },
 { name: 'Interference', description: 'A player impedes an opponent who does not have the puck, resulting in a penalty.' },
 //{ name: 'Penalty Shot', description: 'Awarded when a player on a breakaway is illegally stopped, giving them a one-on-one attempt against the goaltender.' },
 { name: 'Penalty Kill', description: 'The shorthanded team successfully defends until their penalized player returns from the penalty box. ⚠️ "Penalty Box" = "Sin Bin" in some European hockey coverage.' },
 { name: 'Post/ Crossbar Hit', description: 'A shot strikes the post or crossbar instead of going in, generating a massive crowd reaction.' },
 { name: 'Delayed Penalty', description: 'The referee raises their arm to signal a penalty but does not blow the whistle, allowing the non-offending team to continue play.' },
 { name: 'Goalie Pull', description: 'The goaltender is removed for an extra attacker late in the game, leaving the net empty.' },
 { name: 'Three Stars', description: 'After each game, three players are announced as the top performers' },
 { name: 'Broken Stick', description: 'A player\'s stick breaks during play, forcing them to drop it and play on or skate to the bench.' },
 { name: 'Five Hole Goal', description: 'A goal scored through the gap between the goaltender\'s legs.' },
 { name: 'Toe Drag', description: 'A player drags the puck with the toe of their stick blade to evade a defender.' },
 { name: 'Coast to Coast', description: 'A player carries the puck the full length of the ice on their own before attempting a shot.' },
 { name: 'Net Dislodged', description: 'The net is knocked off its moorings during play, stopping the game while it is reset.' },
 { name: 'Two Man Advantage', description: 'Both teams have a player in the penalty box simultaneously, creating a 5-on-3 power play for one team.' },
 { name: 'Takeaway', description: 'A defensive player cleanly steals the puck from an opponent without drawing a penalty.' },
 { name: 'Power Play Goal', description: 'A goal scored while the opposing team has a player in the penalty box. ⚠️ "Penalty Box" = "Sin Bin" in some European hockey coverage.' },
 { name: 'Too Many Men on Ice', description: 'A team has more players on the ice than permitted, resulting in a bench minor penalty.' },
 { name: 'Goal Under Review', description: 'A goal is sent to the NHL Situation Room for video review to confirm or overturn the call.' },
 { name: 'Goaltender Interference', description: 'An attacking player illegally impedes the goalie, often resulting in a goal being disallowed after review.' },
 { name: 'Puck Over Glass', description: 'A player shoots the puck out of play from their defensive zone, resulting in a delay of game penalty.' },
 { name: 'Charging', description: 'A player takes too many strides before delivering a body check, resulting in a penalty.' },
 { name: 'Roughing', description: 'A minor physical altercation between players that falls short of a full fight, resulting in coincidental penalties.' },
 { name: 'Dive/ Embellishment', description: 'A player exaggerates or fakes contact to deceive the referee into calling a foul, generating a strong crowd reaction.' },
 { name: 'Coach\'s Challenge', description: 'A coach requests a video review of a specific call, risking a penalty if the challenge fails.' },
 { name: 'Overtime Goal', description: 'A goal scored during overtime, immediately ending the game. A sudden-death moment that generates one of the loudest crowd reactions in hockey.' },
 { name: 'Player Ejected', description: 'A player is thrown out of the game by the referee for accumulating penalties or committing a serious infraction, distinct from a fight-related ejection.' },
 { name: 'Encroachment', description: 'A player enters the face-off circle before the puck is dropped, causing the referee to reset the face-off.' },
 { name: 'Checking from Behind', description: 'A player hits an opponent from behind, driving them into the boards.' },
 { name: '4-on-4', description: 'Both teams have a player in the penalty box simultaneously, creating 4-on-4 play on the ice.' },
 { name: 'Stick Tap', description: 'A player taps their stick on the ice to acknowledge a teammate after a goal or big play.' },
 { name: 'Dangle', description: 'A player uses creative, deceptive stick-handling to get past a defender. A broader skill move of which the Toe Drag is a specific technique.' },
 { name: 'Face Paint', description: 'A fan has painted their face in team colors.' },
 { name: 'Beer Cup', description: 'A fan is seen with a beer.' },
 { name: 'Goal Horn', description: 'The arena\'s goal horn blares immediately after a goal is scored.' },
 { name: 'Retro Jersey', description: 'A fan wears a classic jersey from a past era of the team.' },
 { name: 'Team Scarf', description: 'A fan wears or holds the team\'s official scarf in the stands.' },
 { name: 'Let\'s Go Chant', description: 'The crowd chants "Let\'s Go [Team Name]!" in unison, the universal hockey fan rallying call.' },
 { name: 'Banner', description: 'A large sign or cloth displayed by fans with a message or team slogan.' },
 { name: 'Hot Dog', description: 'A fan is eating a hot dog.' },
 { name: 'National Anthem', description: 'The national anthem is performed before the game, with hockey fans participation.' },
 { name: 'Organ Music', description: 'The arena organ plays between whistles and during stoppages' },
 { name: 'Fan Roar', description: 'The entire arena erupts in noise simultaneously, usually after a big play or goal.' },
 { name: 'Pound the Glass', description: 'Fans bang on the glass boards surrounding the rink to energize the crowd or react to a big hit near the boards.' },
 { name: 'Rally Towel', description: 'Fans wave rally towels to energize the crowd during a big moment, a tradition dating to the 1982 Vancouver Canucks.' },
 { name: 'Dance Cam', description: 'The jumbotron highlights a fan dancing energetically in the stands.' },
 { name: 'Mascot on Ice', description: 'The team mascot appears on the ice during an intermission, performing or interacting with fans.' },
 { name: 'Painted Chest', description: 'A fan has painted their torso in team colors.' },
 //{ name: 'Hat Toss', description: 'Fans throw hats onto the ice after a player scores three goals.' },
 //{ name: 'Playoff Beard', description: 'Players grow beards throughout the playoffs without shaving.' },
 { name: 'Zamboni on Ice', description: 'The Zamboni resurfaces the ice between periods.' },
 //{ name: 'Octopus Toss', description: 'Detroit Red Wings fans throw an octopus onto the ice during playoff games.' },
 //{ name: 'Fan Tears', description: 'A fan is visibly crying, from joy or heartbreak, captured by broadcast cameras.' },
 //{ name: 'Timeout', description: 'A team calls their one allotted timeout per game, almost always used in the final minute of a close game.' },
];

const americanFootballItems: BingoItem[] = [
 { name: 'Touchdown', description: 'A player carries or catches the ball in the opposing team\'s end zone, scoring six points.' },
 { name: 'Field Goal', description: 'A kicker kicks the ball through the upright posts, scoring three points.' },
 { name: 'Interception', description: 'A defensive player catches a pass intended for the opposing offense, turning over possession.' },
 { name: 'Fumble', description: 'A player loses control of the ball while in possession, making it available for either team to recover.' },
 { name: 'Sack', description: 'A defensive player tackles the quarterback behind the line of scrimmage before he can throw the ball.' },
 { name: 'First Down', description: 'The offense gains at least ten yards within four plays, earning a fresh set of downs.' },
 { name: 'Extra Point', description: 'After a touchdown, the kicking team attempts a one-point kick through the uprights.' },
 { name: 'Punt', description: 'The offense kicks the ball to the opposing team on fourth down rather than risk a turnover on downs.' },
 //{ name: 'Safety', description: 'A defensive player tackles the ball carrier in their own end zone, scoring two points for the defense.' },
 { name: 'Two-Point Conv.', description: 'After a touchdown, the offense runs or passes the ball into the end zone for two points instead of kicking.' },
 //{ name: 'Onside Kick', description: 'The kicking team attempts a short kickoff to recover the ball rather than kick it deep.' },
 { name: 'Blitz', description: 'The defense sends extra rushers at the quarterback beyond the standard four pass rushers.' },
 { name: 'Challenge Flag', description: 'A coach throws a red flag onto the field to request a video review of a specific referee call.' },
 { name: 'Kickoff Return', description: 'A player catches the kickoff and runs it back toward the opposing end zone.' },
 //{ name: 'Fake Punt', description: 'The punting team lines up as if to punt but instead runs or passes the ball to gain a first down.' },
 { name: 'Screen Pass', description: 'The quarterback throws a short pass to a receiver who has blockers set up in front of them.' },
 { name: 'Coin Toss', description: 'Before the game, team captains meet at midfield to determine who receives the ball first.' },
 //{ name: 'Overtime', description: 'The game is tied at the end of regulation and continues with additional play until a winner is determined.' },
 { name: 'Huddle', description: 'Players gather in a circle to hear the play call from the quarterback before lining up.' },
 { name: 'Timeout', description: 'A team stops the clock to rest, strategize, or prevent a penalty.' },
 { name: 'Incomplete Pass', description: 'A forward pass hits the ground before being caught, stopping the clock and ending the play.' },
 { name: 'QB Sneak', description: 'The quarterback takes the snap and immediately dives forward behind the center for short yardage.' },
 //{ name: 'Blocked Kick', description: 'A defensive player gets their hand on a field goal or extra point attempt, preventing it from scoring.' },
 { name: 'End Zone Dance', description: 'A player scores a touchdown and performs a celebratory dance or routine in the end zone.' },
 { name: 'Spike Ball', description: 'The quarterback throws the ball into the ground immediately after the snap to stop the clock.' },
 { name: 'Pick Six', description: 'A defensive player intercepts a pass and returns it all the way for a touchdown.' },
 { name: 'Rushing Touchdown', description: 'A player scores a touchdown by running the ball into the end zone.' },
 { name: 'Passing Touchdown', description: 'A quarterback throws the ball to a receiver who catches it in the end zone for a score.' },
 { name: 'No Huddle Offense', description: 'The offense skips the huddle and snaps the ball quickly to prevent the defense from substituting.' },
 { name: 'Two-Minute Warning', description: 'An automatic timeout called when two minutes remain in each half, always a broadcast focus moment.' },
 { name: 'Goal Line Stand', description: 'The defense stops the offense from scoring when they have the ball inside the one-yard line.' },
 { name: 'Turnover on Downs', description: 'The offense fails to gain a first down on fourth down and surrenders possession to the defense.' },
 { name: 'Fair Catch', description: 'A punt returner signals they will catch the ball without being tackled by raising one hand.' },
 { name: 'Touchback', description: 'A kickoff or punt lands in or is downed in the end zone, giving the receiving team the ball at the 25-yard line.' },
 { name: 'Hurry Up Offense', description: 'The offense rapidly runs plays without huddling to stop the clock late in the game.' },
 { name: 'Play Action', description: 'The quarterback fakes a handoff to a runner before dropping back to pass, designed to freeze the defense.' },
 //{ name: 'Lateral Pass', description: 'A sideways or backward pass, often used as a last-ditch desperation play at the end of a game.' },
 { name: 'Red Zone Touchdown', description: 'A touchdown scored from inside the opposing team\'s 20-yard line.' },
 { name: 'False Start', description: 'An offensive player moves before the ball is snapped, resulting in a five-yard penalty.' },
 { name: 'Offensive Holding', description: 'An offensive player illegally grabs or restrains a defender, resulting in a ten-yard penalty.' },
 { name: 'Defensive Pass Interference', description: 'A defensive player illegally contacts a receiver before the ball arrives, giving the offense the ball at the spot of the foul.' },
 { name: 'Roughing the Passer', description: 'A defensive player makes illegal contact with the quarterback after he has thrown the ball, resulting in a 15-yard penalty.' },
 { name: 'Face Mask', description: 'A player grabs another player\'s face mask during a tackle, resulting in a 15-yard penalty.' },
 { name: 'Delay of Game', description: 'The offense fails to snap the ball before the play clock expires, resulting in a five-yard penalty.' },
 { name: 'Missed Field Goal', description: 'The kicker\'s field goal attempt goes wide or falls short of the uprights, turning the ball over to the defense.' },
 { name: 'Defensive Holding', description: 'A defensive player illegally grabs a receiver or runner before the ball arrives, resulting in a five-yard penalty and automatic first down.' },
 //{ name: 'Unsportsmanlike Conduct', description: 'A player or coach acts in an unsportsmanlike manner, resulting in a 15-yard penalty.' },
 { name: '4th Down Conversion', description: 'The offense successfully gains a first down on fourth down instead of punting or kicking.' },
 { name: 'Replay Review', description: 'Officials in the booth automatically review a play using video, typically in the final two minutes of each half.' },
 { name: 'Kickoff', description: 'The kicking team starts each half and restarts play after each score by kicking the ball from their own 35-yard line.' },
 { name: 'Muffed Punt', description: 'The punt returner fails to catch or control the ball, giving the kicking team a chance to recover possession.' },
 { name: 'Punt Return', description: 'A player catches the punt and runs it back toward the opposing end zone for positive yardage.' },
 { name: 'Fumble Return', description: 'A defensive player recovers a fumble and returns it for yards or a touchdown.' },
 { name: 'QB Scramble', description: 'The quarterback runs with the ball instead of passing, either by design or when the pass play breaks down.' },
 { name: 'Stripped Ball', description: 'A defender deliberately knocks the ball out of a ball carrier\'s hands, causing a fumble.' },
 { name: 'Trick Play', description: 'A deceptive play disguised as a standard formation, such as a wide receiver throwing a pass, a double reverse, or a fake spike, designed to catch the defense completely off guard.' },
 { name: 'One-Handed Catch', description: 'A receiver catches the ball using only one hand.' },
 { name: 'Penalty Declined', description: 'The non-offending team chooses not to accept a called penalty because the result of the play was more beneficial than what the penalty would award them.' },
 { name: 'QB Kneel', description: 'The quarterback takes the snap and immediately drops to one knee to run time off the clock, used to protect a lead at the end of a game.' },
 { name: 'Dropped Pass', description: 'A receiver fails to catch a catchable ball thrown accurately by the quarterback, generating a crowd reaction.' },
 { name: 'Third Down Conversion', description: 'The offense successfully gains a first down on third down, keeping their drive alive.' },
 { name: 'Face Paint', description: 'A fan has painted their face in team colors.' },
 { name: 'Cheerleaders', description: 'The team\'s official cheer squad performs on the sideline or during timeouts.' },
 { name: 'Beer Cup', description: 'A fan is seen with a beer.' },
 { name: 'Marching Band', description: 'A live band performs in the stadium, energizing the crowd before the game or at halftime.' },
 { name: 'Painted Chest', description: 'A fan has painted their torso in team colors.' },
 { name: 'Fan Sign', description: 'A fan holds up a visible handmade sign.' },
 { name: 'Flag Waving', description: 'A fan waves a large team or national flag in the stands.' },
 { name: 'Stadium Wave', description: 'Fans stand and raise their arms in sequence around the stadium, creating a ripple effect.' },
 { name: 'Fan Roar', description: 'The entire stadium erupts in noise simultaneously, usually after a big play.' },
 { name: 'National Anthem', description: 'The national anthem is performed before the game with fans standing and removing their hats.' },
 { name: 'Foam Finger', description: 'A fan holds up an oversized foam finger in team colors, a classic football fan accessory.' },
 { name: 'Defense Chant', description: 'The crowd chants "Defense!" in unison, clapping in rhythm to pressure the opposing offense.' },
 { name: 'Rally Towel', description: 'Fans wave rally towels overhead to energize the crowd during a big moment.' },
 { name: 'Celebrity in the Stands', description: 'The broadcast cuts to a recognizable celebrity watching the game from the stands.' },
 //{ name: 'Hail Mary', description: 'A long desperation pass thrown to the end zone at the end of a half, with multiple receivers fighting for the ball.' },
 //{ name: 'Roughing the Kicker', description: 'A defensive player makes illegal contact with the punter or kicker after they have released the ball, resulting in a 15-yard penalty. Occurs in only about 2% of games.' },
];

export function getBingoItems(sport: Sport): BingoItem[] {
  switch (sport) {
    case 'soccer':
      return soccerItems;
    case 'americanFootball':
      return americanFootballItems;
    case 'baseball':
      return baseballItems;
    case 'basketball':
      return basketballItems;
    case 'rugby':
      return rugbyItems;
    case 'hockey':
      return hockeyItems;
    default:
      return soccerItems;
  }
}
